// src/components/dashboard/student/StudentDash.tsx
import React, { useState } from 'react';
import { useEMIS } from '@/contexts/EMISContext';
import { useRegistration } from '@/contexts/RegistrationContext';
import { StatCard, Badge, PageHeader, Button, Table, Toast } from '@/components/shared/UI';
import { FileText, Award, Download, History, GraduationCap, CreditCard } from 'lucide-react';
import StudentRegistration from './StudentRegistration';
import StudentResults from './StudentResults';
import StudentHistory from './StudentHistory';

const StudentDash: React.FC<{ active: string }> = ({ active }) => {
  const { currentUser, courses = [] } = useEMIS();
  const { getStudentInvoices, getStudentRegistrations } = useRegistration();
  const [toast, setToast] = useState('');

  // Temporary empty results array until results API is built
  const myResults: any[] = [];
  const myInvoices = getStudentInvoices(currentUser?.id || '') || [];
  const myRegistrations = getStudentRegistrations(currentUser?.id || '') || [];

  const downloadPDF = () => {
    const html = `
      <html><head><title>Result Slip - ${currentUser?.name}</title>
      <style>body{font-family:Arial;padding:40px;}h1{color:#1e3a8a;border-bottom:3px solid #1e3a8a;padding-bottom:10px;}table{width:100%;border-collapse:collapse;margin-top:20px;}th,td{border:1px solid #ddd;padding:8px;text-align:left;}th{background:#1e3a8a;color:white;}.head{margin-bottom:20px;}.label{font-weight:bold;color:#555;}</style>
      </head><body>
      <h1>OFFICIAL RESULT SLIP</h1>
      <div class="head">
        <p><span class="label">Name:</span> ${currentUser?.name}</p>
        <p><span class="label">Registration No:</span> ${(currentUser as any)?.regNumber}</p>
        <p><span class="label">Program:</span> ${(currentUser as any)?.program || 'N/A'}</p>
        <p><span class="label">Issued:</span> ${new Date().toLocaleDateString()}</p>
      </div>
      <table><thead><tr><th>Course</th><th>Exam</th><th>Grade</th></table></thead>
      <tbody><tr><td colspan="3">No results available yet</td></tr></tbody>
      </table>
      <p style="margin-top:40px;color:#666;font-size:12px;">This is an official document generated by EMIS. All approved results are permanently locked.</p>
      </body></html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const win = window.open(url);
    if (win) setTimeout(() => win.print(), 500);
  };

  const avgTotal = 0;
  const passed = 0;
  const isRegistered = (myRegistrations || []).some(r => r.registrationStatus === 'approved');
  const hasPendingInvoice = (myInvoices || []).some(i => i.status === 'pending' || i.status === 'paid');

  // ========== DASHBOARD VIEW ==========
  if (active === 'dashboard') {
    return (
      <div>
        {toast && <Toast message={toast} onClose={() => setToast('')} />}
        <PageHeader title={`Welcome, ${currentUser?.name?.split(' ')[0]}`} subtitle="Your academic results portal" />

        {/* Registration Status Banner */}
        {!isRegistered && (
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6 flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center gap-3">
              <CreditCard className="w-6 h-6 text-amber-600" />
              <div>
                <p className="font-medium text-amber-800">Registration Required</p>
                <p className="text-sm text-amber-700">You need to register for your level to access full features</p>
              </div>
            </div>
            <Button variant="secondary" className="bg-amber-100 text-amber-800 hover:bg-amber-200">
              Go to Registration
            </Button>
          </div>
        )}

        {hasPendingInvoice && (
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-6 flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center gap-3">
              <ClockIcon className="w-6 h-6 text-blue-600" />
              <div>
                <p className="font-medium text-blue-800">Payment Pending Approval</p>
                <p className="text-sm text-blue-700">Your receipt is being verified by Accounts department</p>
              </div>
            </div>
          </div>
        )}

        <div className="bg-gradient-to-r from-indigo-700 to-blue-700 rounded-xl p-6 text-white mb-6">
          <div className="flex items-start justify-between flex-wrap gap-4">
            <div>
              <p className="text-blue-200 text-sm">Student Profile</p>
              <h2 className="text-2xl font-bold mt-1">{currentUser?.name}</h2>
              <p className="font-mono text-sm mt-1 text-blue-100">{(currentUser as any)?.regNumber}</p>
              <p className="text-sm mt-1 text-blue-200">{(currentUser as any)?.program} • {(currentUser as any)?.level}</p>
            </div>
            <div className="bg-white/10 p-4 rounded-lg"><GraduationCap className="w-12 h-12" /></div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
          <StatCard label="Approved Results" value={myResults.length} icon={FileText} color="bg-emerald-600" />
          <StatCard label="Courses Passed" value={passed} icon={Award} color="bg-blue-600" />
          <StatCard label="Average Score" value={avgTotal} icon={Award} color="bg-purple-600" sub="Out of 100" />
          <StatCard label="Failed" value={myResults.length - passed} icon={History} color="bg-amber-600" />
        </div>

        <div className="bg-white border border-slate-200 rounded-xl p-5">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-slate-900">Latest Approved Results</h3>
            <Button onClick={downloadPDF}><Download className="w-4 h-4 inline mr-1" />Download PDF</Button>
          </div>
          <Table headers={['Course', 'Exam', 'Grade']} rowCount={0}>
            <tr><td colSpan={3} className="text-center py-8 text-slate-500">No results available yet</td></tr>
          </Table>
        </div>
      </div>
    );
  }

  // ========== REGISTRATION VIEW ==========
  if (active === 'registration') {
    return <StudentRegistration toast={toast} setToast={setToast} />;
  }

  // ========== RESULTS VIEW ==========
  if (active === 'results') {
    return <StudentResults downloadPDF={downloadPDF} />;
  }

  // ========== INVOICES VIEW ==========
  if (active === 'invoices') {
    return (
      <div>
        <PageHeader title="My Invoices" subtitle="Track your payment history" />
        <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
          <Table headers={['Invoice #', 'Level', 'Amount', 'Status', 'Date', 'Actions']} rowCount={(myInvoices || []).length}>
            {(myInvoices || []).map(inv => (
              <tr key={inv.id} className="hover:bg-slate-50">
                <td className="px-4 py-3 font-mono text-xs">#{inv.id.slice(-8)}</td>
                <td className="px-4 py-3">Level {inv.level}</td>
                <td className="px-4 py-3 font-medium">K{inv.amount.toLocaleString()}</td>
                <td className="px-4 py-3">
                  {inv.status === 'pending' && <Badge status="warning">Pending</Badge>}
                  {inv.status === 'paid' && <Badge status="info">Receipt Uploaded</Badge>}
                  {inv.status === 'approved' && <Badge status="success">Approved</Badge>}
                  {inv.status === 'rejected' && <Badge status="error">Rejected</Badge>}
                </td>
                <td className="px-4 py-3 text-xs">{new Date(inv.createdAt).toLocaleDateString()}</td>
                <td className="px-4 py-3">
                  {(inv.status === 'pending' || inv.status === 'rejected') && (
                    <Button variant="secondary" className="px-3 py-1.5 text-sm">Upload Receipt</Button>
                  )}
                </td>
              </tr>
            ))}
          </Table>
        </div>
      </div>
    );
  }

  // ========== DOWNLOAD VIEW ==========
  if (active === 'download') {
    return (
      <div>
        <PageHeader title="Download Results" subtitle="Generate official PDF result slip" />
        <div className="bg-white border border-slate-200 rounded-xl p-8 text-center max-w-2xl mx-auto">
          <div className="bg-blue-50 p-4 rounded-full w-20 h-20 mx-auto mb-4 flex items-center justify-center">
            <Download className="w-10 h-10 text-blue-700" />
          </div>
          <h3 className="text-xl font-bold text-slate-900 mb-2">Official Result Slip</h3>
          <p className="text-slate-600 mb-6">Generate a printable PDF of all your approved results.</p>
          <div className="bg-slate-50 p-4 rounded-lg mb-6 text-left">
            <p className="text-sm"><span className="font-medium">Student:</span> {currentUser?.name}</p>
            <p className="text-sm"><span className="font-medium">Reg No:</span> {(currentUser as any)?.regNumber}</p>
            <p className="text-sm"><span className="font-medium">Approved Results:</span> {myResults.length}</p>
          </div>
          <Button onClick={downloadPDF}><Download className="w-4 h-4 inline mr-1" />Generate PDF</Button>
        </div>
      </div>
    );
  }

  // ========== HISTORY VIEW ==========
  if (active === 'history') {
    return <StudentHistory />;
  }

  return null;
};

// Clock Icon component
const ClockIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
  </svg>
);

export default StudentDash;