// src/components/dashboard/student/StudentDash.tsx
import React, { useState } from 'react';
import { useEMIS } from '@/contexts/EMISContext';
import { useRegistration } from '@/contexts/RegistrationContext';
import { StatCard, Badge, PageHeader, Button, Table, Toast } from '@/components/shared/UI';
import { FileText, Award, Download, History, GraduationCap, CreditCard } from 'lucide-react';
import StudentRegistration from './StudentRegistration';
import StudentResults from './StudentResults';
import StudentHistory from './StudentHistory';

const StudentDash: React.FC<{ active: string }> = ({ active }) => {
  const { currentUser, courses, results } = useEMIS();
  const { getStudentInvoices, getStudentRegistrations } = useRegistration();
  const [toast, setToast] = useState('');

  const myResults = results.filter(r => r.studentId === currentUser?.id && r.status === 'approved');
  const myInvoices = getStudentInvoices(currentUser?.id || '');
  const myRegistrations = getStudentRegistrations(currentUser?.id || '');

  const downloadPDF = () => {
    const html = `
      <html><head><title>Result Slip - ${currentUser?.name}</title>
      <style>body{font-family:Arial;padding:40px;}h1{color:#1e3a8a;border-bottom:3px solid #1e3a8a;padding-bottom:10px;}table{width:100%;border-collapse:collapse;margin-top:20px;}th,td{border:1px solid #ddd;padding:8px;text-align:left;}th{background:#1e3a8a;color:white;}.head{margin-bottom:20px;}.label{font-weight:bold;color:#555;}</style>
      </head><body>
      <h1>OFFICIAL RESULT SLIP</h1>
      <div class="head">
        <p><span class="label">Name:</span> ${currentUser?.name}</p>
        <p><span class="label">Registration No:</span> ${(currentUser as any)?.regNumber}</p>
        <p><span class="label">Program:</span> ${(currentUser as any)?.program || 'N/A'}</p>
        <p><span class="label">Issued:</span> ${new Date().toLocaleDateString()}</p>
      </div>
      <table><thead><tr><th>Course</th><th>Exam</th><th>Grade</th></tr></thead>
      <tbody>${myResults.map(r => `<tr><td>${courses.find(c => c.id === r.courseId)?.name || 'N/A'}</td><td>${r.exam ?? '-'}</td><td><b>${r.grade}</b></td>`).join('')}</tbody></table>
      <p style="margin-top:40px;color:#666;font-size:12px;">This is an official document generated by EMIS. All approved results are permanently locked.</p>
      </body></html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const win = window.open(url);
    if (win) setTimeout(() => win.print(), 500);
  };

  const avgTotal = myResults.length ? Math.round(myResults.reduce((s, r) => s + (r.exam || 0), 0) / myResults.length) : 0;
  const passed = myResults.filter(r => r.grade !== 'F' && r.grade !== 'INC').length;
  const isRegistered = myRegistrations.some(r => r.registrationStatus === 'approved');
  const hasPendingInvoice = myInvoices.some(i => i.status === 'pending' || i.status === 'paid');

  // ========== DASHBOARD VIEW ==========
  if (active === 'dashboard') {
    return (
      <div>
        {toast && <Toast message={toast} onClose={() => setToast('')} />}
        <PageHeader title={`Welcome, ${currentUser?.name?.split(' ')[0]}`} subtitle="Your academic results portal" />

        {/* Registration Status Banner */}
        {!isRegistered && (
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6 flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center gap-3">
              <CreditCard className="w-6 h-6 text-amber-600" />
              <div>
                <p className="font-medium text-amber-800">Registration Required</p>
                <p className="text-sm text-amber-700">You need to register for your level to access full features</p>
              </div>
            </div>
            <Button variant="secondary" className="bg-amber-100 text-amber-800 hover:bg-amber-200">
              Go to Registration
            </Button>
          </div>
        )}

        {hasPendingInvoice && (
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-6 flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center gap-3">
              <ClockIcon className="w-6 h-6 text-blue-600" />
              <div>
                <p className="font-medium text-blue-800">Payment Pending Approval</p>
                <p className="text-sm text-blue-700">Your receipt is being verified by Accounts department</p>
              </div>
            </div>
          </div>
        )}

        <div className="bg-gradient-to-r from-indigo-700 to-blue-700 rounded-xl p-6 text-white mb-6">
          <div className="flex items-start justify-between flex-wrap gap-4">
            <div>
              <p className="text-blue-200 text-sm">Student Profile</p>
              <h2 className="text-2xl font-bold mt-1">{currentUser?.name}</h2>
              <p className="font-mono text-sm mt-1 text-blue-100">{(currentUser as any)?.regNumber}</p>
              <p className="text-sm mt-1 text-blue-200">{(currentUser as any)?.program} • {(currentUser as any)?.level}</p>
            </div>
            <div className="bg-white/10 p-4 rounded-lg"><GraduationCap className="w-12 h-12" /></div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
          <StatCard label="Approved Results" value={myResults.length} icon={FileText} color="bg-emerald-600" />
          <StatCard label="Courses Passed" value={passed} icon={Award} color="bg-blue-600" />
          <StatCard label="Average Score" value={avgTotal} icon={Award} color="bg-purple-600" sub="Out of 100" />
          <StatCard label="Failed" value={myResults.length - passed} icon={History} color="bg-amber-600" />
        </div>

        <div className="bg-white border border-slate-200 rounded-xl p-5">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-slate-900">Latest Approved Results</h3>
            <Button onClick={downloadPDF}><Download className="w-4 h-4 inline mr-1" />Download PDF</Button>
          </div>
          <Table headers={['Course', 'Exam', 'Grade']} rowCount={Math.min(myResults.length, 5)}>
            {myResults.slice(0, 5).map(r => (
              <tr key={r.id}>
                <td className="px-4 py-3 text-xs">{courses.find(c => c.id === r.courseId)?.name || '—'}</td>
                <td className="px-4 py-3 text-center font-medium">{r.exam ?? '—'}</td>
                <td className="px-4 py-3 text-center">
                  <span className={`font-bold ${r.grade === 'F' ? 'text-red-600' : 'text-emerald-600'}`}>
                    {r.grade}
                  </span>
                </td>
              </tr>
            ))}
          </Table>
        </div>
      </div>
    );
  }

  // ========== REGISTRATION VIEW ==========
  if (active === 'registration') {
    return <StudentRegistration toast={toast} setToast={setToast} />;
  }

  // ========== RESULTS VIEW ==========
  if (active === 'results') {
    return <StudentResults downloadPDF={downloadPDF} />;
  }

  // ========== INVOICES VIEW ==========
  if (active === 'invoices') {
    return (
      <div>
        <PageHeader title="My Invoices" subtitle="Track your payment history" />
        <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
          <Table headers={['Invoice #', 'Level', 'Amount', 'Status', 'Date', 'Actions']} rowCount={myInvoices.length}>
            {myInvoices.map(inv => (
              <tr key={inv.id} className="hover:bg-slate-50">
                <td className="px-4 py-3 font-mono text-xs">#{inv.id.slice(-8)}</td>
                <td className="px-4 py-3">Level {inv.level}</td>
                <td className="px-4 py-3 font-medium">K{inv.amount.toLocaleString()}</td>
                <td className="px-4 py-3">
                  {inv.status === 'pending' && <Badge status="warning">Pending</Badge>}
                  {inv.status === 'paid' && <Badge status="info">Receipt Uploaded</Badge>}
                  {inv.status === 'approved' && <Badge status="success">Approved</Badge>}
                  {inv.status === 'rejected' && <Badge status="error">Rejected</Badge>}
                </td>
                <td className="px-4 py-3 text-xs">{new Date(inv.createdAt).toLocaleDateString()}</td>
                <td className="px-4 py-3">
                  {(inv.status === 'pending' || inv.status === 'rejected') && (
                    <Button variant="secondary" className="px-3 py-1.5 text-sm">Upload Receipt</Button>
                  )}
                </td>
              </tr>
            ))}
          </Table>
        </div>
      </div>
    );
  }

  // ========== DOWNLOAD VIEW ==========
  if (active === 'download') {
    return (
      <div>
        <PageHeader title="Download Results" subtitle="Generate official PDF result slip" />
        <div className="bg-white border border-slate-200 rounded-xl p-8 text-center max-w-2xl mx-auto">
          <div className="bg-blue-50 p-4 rounded-full w-20 h-20 mx-auto mb-4 flex items-center justify-center">
            <Download className="w-10 h-10 text-blue-700" />
          </div>
          <h3 className="text-xl font-bold text-slate-900 mb-2">Official Result Slip</h3>
          <p className="text-slate-600 mb-6">Generate a printable PDF of all your approved results.</p>
          <div className="bg-slate-50 p-4 rounded-lg mb-6 text-left">
            <p className="text-sm"><span className="font-medium">Student:</span> {currentUser?.name}</p>
            <p className="text-sm"><span className="font-medium">Reg No:</span> {(currentUser as any)?.regNumber}</p>
            <p className="text-sm"><span className="font-medium">Approved Results:</span> {myResults.length}</p>
          </div>
          <Button onClick={downloadPDF}><Download className="w-4 h-4 inline mr-1" />Generate PDF</Button>
        </div>
      </div>
    );
  }

  // ========== HISTORY VIEW ==========
  if (active === 'history') {
    return <StudentHistory />;
  }

  return null;
};

// Clock Icon component
const ClockIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
  </svg>
);

export default StudentDash;

// // src/components/dashboard/student/StudentDash.tsx
// import React, { useMemo, useState } from 'react';
// import { useEMIS } from '@/contexts/EMISContext';
// import { useRegistration } from '@/contexts/RegistrationContext';
// import { StatCard, Badge, PageHeader, Button, Table, Input, Select, Toast } from '@/components/shared/UI';
// import { FileText, Award, Download, History, GraduationCap, CreditCard } from 'lucide-react';
// import StudentRegistration from './StudentRegistration';

// const StudentDash: React.FC<{ active: string }> = ({ active }) => {
//   const { currentUser, courses, modules, results, sessions } = useEMIS();
//   const { getStudentInvoices, getStudentRegistrations } = useRegistration();
//   const [toast, setToast] = useState('');

//   const myResults = results.filter(r => r.studentId === currentUser?.id && r.status === 'approved');
//   const myInvoices = getStudentInvoices(currentUser?.id || '');
//   const myRegistrations = getStudentRegistrations(currentUser?.id || '');

//   const [filters, setFilters] = useState({ courseId: '', moduleId: '', sessionId: '' });

//   const filtered = useMemo(() => myResults.filter(r =>
//     (!filters.courseId || r.courseId === filters.courseId) &&
//     (!filters.moduleId || r.moduleId === filters.moduleId) &&
//     (!filters.sessionId || r.sessionId === filters.sessionId)
//   ), [myResults, filters]);

//   const downloadPDF = () => {
//     const html = `
//       <html><head><title>Result Slip - ${currentUser?.name}</title>
//       <style>body{font-family:Arial;padding:40px;}h1{color:#1e3a8a;border-bottom:3px solid #1e3a8a;padding-bottom:10px;}table{width:100%;border-collapse:collapse;margin-top:20px;}th,td{border:1px solid #ddd;padding:8px;text-align:left;}th{background:#1e3a8a;color:white;}.head{margin-bottom:20px;}.label{font-weight:bold;color:#555;}</style>
//       </head><body>
//       <h1>OFFICIAL RESULT SLIP</h1>
//       <div class="head">
//         <p><span class="label">Name:</span> ${currentUser?.name}</p>
//         <p><span class="label">Registration No:</span> ${(currentUser as any)?.regNumber}</p>
//         <p><span class="label">Program:</span> ${(currentUser as any)?.program || 'N/A'}</p>
//         <p><span class="label">Issued:</span> ${new Date().toLocaleDateString()}</p>
//       </div>
//       <table><thead><tr><th>Course</th><th>Module</th><th>CA</th><th>Exam</th><th>Total</th><th>Grade</th></tr></thead>
//       <tbody>${myResults.map(r => `<tr><td>${courses.find(c => c.id === r.courseId)?.code}</td><td>${modules.find(m => m.id === r.moduleId)?.code}</td><td>${r.ca ?? '-'}</td><td>${r.exam ?? '-'}</td><td>${r.total ?? '-'}</td><td><b>${r.grade}</b></td></tr>`).join('')}</tbody></table>
//       <p style="margin-top:40px;color:#666;font-size:12px;">This is an official document generated by EMIS. All approved results are permanently locked.</p>
//       </body></html>`;
//     const blob = new Blob([html], { type: 'text/html' });
//     const url = URL.createObjectURL(blob);
//     const win = window.open(url);
//     if (win) setTimeout(() => win.print(), 500);
//   };

//   const avgTotal = myResults.length ? Math.round(myResults.reduce((s, r) => s + (r.total || 0), 0) / myResults.length) : 0;
//   const passed = myResults.filter(r => r.grade !== 'F' && r.grade !== 'INC').length;
//   const isRegistered = myRegistrations.some(r => r.registrationStatus === 'approved');
//   const hasPendingInvoice = myInvoices.some(i => i.status === 'pending' || i.status === 'paid');

//   // ========== DASHBOARD VIEW ==========
//   if (active === 'dashboard') {
//     return (
//       <div>
//         {toast && <Toast message={toast} onClose={() => setToast('')} />}
//         <PageHeader title={`Welcome, ${currentUser?.name?.split(' ')[0]}`} subtitle="Your academic results portal" />

//         {/* Registration Status Banner */}
//         {!isRegistered && (
//           <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6 flex items-center justify-between flex-wrap gap-4">
//             <div className="flex items-center gap-3">
//               <CreditCard className="w-6 h-6 text-amber-600" />
//               <div>
//                 <p className="font-medium text-amber-800">Registration Required</p>
//                 <p className="text-sm text-amber-700">You need to register for your level to access full features</p>
//               </div>
//             </div>
//             <Button variant="secondary" className="bg-amber-100 text-amber-800 hover:bg-amber-200">
//               Go to Registration
//             </Button>
//           </div>
//         )}

//         {hasPendingInvoice && (
//           <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-6 flex items-center justify-between flex-wrap gap-4">
//             <div className="flex items-center gap-3">
//               <ClockIcon className="w-6 h-6 text-blue-600" />
//               <div>
//                 <p className="font-medium text-blue-800">Payment Pending Approval</p>
//                 <p className="text-sm text-blue-700">Your receipt is being verified by Accounts department</p>
//               </div>
//             </div>
//           </div>
//         )}

//         <div className="bg-gradient-to-r from-indigo-700 to-blue-700 rounded-xl p-6 text-white mb-6">
//           <div className="flex items-start justify-between flex-wrap gap-4">
//             <div>
//               <p className="text-blue-200 text-sm">Student Profile</p>
//               <h2 className="text-2xl font-bold mt-1">{currentUser?.name}</h2>
//               <p className="font-mono text-sm mt-1 text-blue-100">{(currentUser as any)?.regNumber}</p>
//               <p className="text-sm mt-1 text-blue-200">{(currentUser as any)?.program} • {(currentUser as any)?.level}</p>
//             </div>
//             <div className="bg-white/10 p-4 rounded-lg"><GraduationCap className="w-12 h-12" /></div>
//           </div>
//         </div>

//         <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
//           <StatCard label="Approved Results" value={myResults.length} icon={FileText} color="bg-emerald-600" />
//           <StatCard label="Modules Passed" value={passed} icon={Award} color="bg-blue-600" />
//           <StatCard label="Average Score" value={avgTotal} icon={Award} color="bg-purple-600" sub="Out of 100" />
//           <StatCard label="Failed/Incomplete" value={myResults.length - passed} icon={History} color="bg-amber-600" />
//         </div>

//         <div className="bg-white border border-slate-200 rounded-xl p-5">
//           <div className="flex items-center justify-between mb-4">
//             <h3 className="font-semibold text-slate-900">Latest Approved Results</h3>
//             <Button onClick={downloadPDF}><Download className="w-4 h-4 inline mr-1" />Download PDF</Button>
//           </div>
//           <Table headers={['Course', 'Module', 'Total', 'Grade']} rowCount={Math.min(myResults.length, 5)}>
//             {myResults.slice(0, 5).map(r => (
//               <tr key={r.id}>
//                 <td className="px-4 py-3 text-xs">{courses.find(c => c.id === r.courseId)?.code} - {courses.find(c => c.id === r.courseId)?.name}</td>
//                 <td className="px-4 py-3 text-xs">{modules.find(m => m.id === r.moduleId)?.code}</td>
//                 <td className="px-4 py-3 text-center font-medium">{r.total ?? '—'}</td>
//                 <td className="px-4 py-3 text-center"><span className={`font-bold ${r.grade === 'F' ? 'text-red-600' : 'text-emerald-600'}`}>{r.grade}</span></td>
//               </tr>
//             ))}
//           </Table>
//           {results.some(r => r.studentId === currentUser?.id && r.status === 'pending') && (
//             <p className="text-xs text-amber-700 bg-amber-50 p-3 rounded mt-3">Note: Some results are still being processed and will appear here once approved.</p>
//           )}
//         </div>
//       </div>
//     );
//   }

//   // ========== REGISTRATION VIEW ==========
//   if (active === 'registration') {
//     return <StudentRegistration toast={toast} setToast={setToast} />;
//   }

//   // ========== RESULTS VIEW ==========
//   if (active === 'results') {
//     return (
//       <div>
//         <PageHeader title="My Results" subtitle="Showing only approved (official) results"
//           action={<Button onClick={downloadPDF}><Download className="w-4 h-4 inline mr-1" />Download PDF</Button>} />
//         <div className="bg-white border border-slate-200 rounded-xl p-4 mb-4 grid grid-cols-1 md:grid-cols-3 gap-3">
//           <Select value={filters.courseId} onChange={e => setFilters({ ...filters, courseId: e.target.value })}>
//             <option value="">All courses</option>
//             {courses.map(c => <option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}
//           </Select>
//           <Select value={filters.moduleId} onChange={e => setFilters({ ...filters, moduleId: e.target.value })}>
//             <option value="">All modules</option>
//             {modules.map(m => <option key={m.id} value={m.id}>{m.code}</option>)}
//           </Select>
//           <Select value={filters.sessionId} onChange={e => setFilters({ ...filters, sessionId: e.target.value })}>
//             <option value="">All sessions</option>
//             {sessions.map(s => <option key={s.id} value={s.id}>{s.year} {s.semester}</option>)}
//           </Select>
//         </div>
//         <Table headers={['Course', 'Module', 'Session', 'CA', 'Exam', 'Total', 'Grade']} rowCount={filtered.length}>
//           {filtered.map(r => (
//             <tr key={r.id} className="hover:bg-slate-50">
//               <td className="px-4 py-3"><div className="font-medium text-xs">{courses.find(c => c.id === r.courseId)?.code}</div><div className="text-xs text-slate-500">{courses.find(c => c.id === r.courseId)?.name}</div></td>
//               <td className="px-4 py-3 text-xs">{modules.find(m => m.id === r.moduleId)?.name}</td>
//               <td className="px-4 py-3 text-xs">{sessions.find(s => s.id === r.sessionId)?.year}</td>
//               <td className="px-4 py-3 text-center">{r.ca ?? '—'}</td>
//               <td className="px-4 py-3 text-center">{r.exam ?? '—'}</td>
//               <td className="px-4 py-3 text-center font-medium">{r.total ?? '—'}</td>
//               <td className="px-4 py-3 text-center"><span className={`font-bold ${r.grade === 'F' ? 'text-red-600' : 'text-emerald-600'}`}>{r.grade}</span></td>
//             </tr>
//           ))}
//         </Table>
//       </div>
//     );
//   }

//   // ========== INVOICES VIEW ==========
//   if (active === 'invoices') {
//     return (
//       <div>
//         <PageHeader title="My Invoices" subtitle="Track your payment history" />
//         <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
//           <Table headers={['Invoice #', 'Level', 'Amount', 'Status', 'Date', 'Actions']} rowCount={myInvoices.length}>
//             {myInvoices.map(inv => (
//               <tr key={inv.id} className="hover:bg-slate-50">
//                 <td className="px-4 py-3 font-mono text-xs">#{inv.id.slice(-8)}</td>
//                 <td className="px-4 py-3">Level {inv.level}</td>
//                 <td className="px-4 py-3 font-medium">K{inv.amount.toLocaleString()}</td>
//                 <td className="px-4 py-3">
//                   {inv.status === 'pending' && <Badge status="warning">Pending</Badge>}
//                   {inv.status === 'paid' && <Badge status="info">Receipt Uploaded</Badge>}
//                   {inv.status === 'approved' && <Badge status="success">Approved</Badge>}
//                   {inv.status === 'rejected' && <Badge status="error">Rejected</Badge>}
//                 </td>
//                 <td className="px-4 py-3 text-xs">{new Date(inv.createdAt).toLocaleDateString()}</td>
//                 <td className="px-4 py-3">
//                   {(inv.status === 'pending' || inv.status === 'rejected') && (
//                     <Button variant="secondary" className="px-3 py-1.5 text-sm">Upload Receipt</Button>
//                   )}
//                 </td>
//               </tr>
//             ))}
//           </Table>
//         </div>
//       </div>
//     );
//   }

//   if (active === 'download') {
//     return (
//       <div>
//         <PageHeader title="Download Results" subtitle="Generate official PDF result slip" />
//         <div className="bg-white border border-slate-200 rounded-xl p-8 text-center max-w-2xl mx-auto">
//           <div className="bg-blue-50 p-4 rounded-full w-20 h-20 mx-auto mb-4 flex items-center justify-center">
//             <Download className="w-10 h-10 text-blue-700" />
//           </div>
//           <h3 className="text-xl font-bold text-slate-900 mb-2">Official Result Slip</h3>
//           <p className="text-slate-600 mb-6">Generate a printable PDF of all your approved results.</p>
//           <div className="bg-slate-50 p-4 rounded-lg mb-6 text-left">
//             <p className="text-sm"><span className="font-medium">Student:</span> {currentUser?.name}</p>
//             <p className="text-sm"><span className="font-medium">Reg No:</span> {(currentUser as any)?.regNumber}</p>
//             <p className="text-sm"><span className="font-medium">Approved Results:</span> {myResults.length}</p>
//           </div>
//           <Button onClick={downloadPDF}><Download className="w-4 h-4 inline mr-1" />Generate PDF</Button>
//         </div>
//       </div>
//     );
//   }

//   if (active === 'history') {
//     const sorted = [...myResults].sort((a, b) => new Date(b.approvedAt || 0).getTime() - new Date(a.approvedAt || 0).getTime());
//     return (
//       <div>
//         <PageHeader title="Result History" subtitle="Timeline of all approved results" />
//         <div className="bg-white border border-slate-200 rounded-xl p-5">
//           <div className="space-y-4">
//             {sorted.length === 0 && <p className="text-center py-12 text-slate-400">No history yet</p>}
//             {sorted.map(r => {
//               const c = courses.find(x => x.id === r.courseId);
//               const m = modules.find(x => x.id === r.moduleId);
//               return (
//                 <div key={r.id} className="flex items-start gap-4 pb-4 border-b border-slate-100 last:border-0">
//                   <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold text-white ${r.grade === 'F' ? 'bg-red-500' : 'bg-emerald-600'}`}>
//                     {r.grade}
//                   </div>
//                   <div className="flex-1">
//                     <div className="flex items-center justify-between flex-wrap">
//                       <p className="font-medium text-slate-900">{c?.code} - {c?.name}</p>
//                       <Badge status="approved" />
//                     </div>
//                     <p className="text-sm text-slate-600">{m?.name}</p>
//                     <div className="flex gap-4 text-xs text-slate-500 mt-1">
//                       <span>CA: {r.ca ?? '—'}</span>
//                       <span>Exam: {r.exam ?? '—'}</span>
//                       <span>Total: {r.total ?? '—'}</span>
//                       <span>Approved: {r.approvedAt ? new Date(r.approvedAt).toLocaleDateString() : '—'}</span>
//                     </div>
//                   </div>
//                 </div>
//               );
//             })}
//           </div>
//         </div>
//       </div>
//     );
//   }

//   return null;
// };

// // Clock Icon component
// const ClockIcon: React.FC<{ className?: string }> = ({ className }) => (
//   <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
//     <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
//   </svg>
// );

// export default StudentDash;

// import React, { useMemo, useState } from 'react';
// import { useEMIS } from '@/contexts/EMISContext';
// import { StatCard, Badge, PageHeader, Button, Table, Input, Select } from '@/components/shared/UI';
// import { FileText, Award, Download, History, GraduationCap } from 'lucide-react';

// const StudentDash: React.FC<{ active: string }> = ({ active }) => {
//   const { currentUser, courses, modules, results, sessions } = useEMIS();
//   const myResults = results.filter(r => r.studentId === currentUser?.id && r.status === 'approved');
//   const [filters, setFilters] = useState({ courseId: '', moduleId: '', sessionId: '' });

//   const filtered = useMemo(() => myResults.filter(r =>
//     (!filters.courseId || r.courseId === filters.courseId) &&
//     (!filters.moduleId || r.moduleId === filters.moduleId) &&
//     (!filters.sessionId || r.sessionId === filters.sessionId)
//   ), [myResults, filters]);

//   const downloadPDF = () => {
//     const html = `
//       <html><head><title>Result Slip - ${currentUser?.name}</title>
//       <style>body{font-family:Arial;padding:40px;}h1{color:#1e3a8a;border-bottom:3px solid #1e3a8a;padding-bottom:10px;}table{width:100%;border-collapse:collapse;margin-top:20px;}th,td{border:1px solid #ddd;padding:8px;text-align:left;}th{background:#1e3a8a;color:white;}.head{margin-bottom:20px;}.label{font-weight:bold;color:#555;}</style>
//       </head><body>
//       <h1>OFFICIAL RESULT SLIP</h1>
//       <div class="head">
//         <p><span class="label">Name:</span> ${currentUser?.name}</p>
//         <p><span class="label">Registration No:</span> ${(currentUser as any)?.regNumber}</p>
//         <p><span class="label">Program:</span> ${(currentUser as any)?.program || 'N/A'}</p>
//         <p><span class="label">Issued:</span> ${new Date().toLocaleDateString()}</p>
//       </div>
//       <table><thead><tr><th>Course</th><th>Module</th><th>CA</th><th>Exam</th><th>Total</th><th>Grade</th></tr></thead>
//       <tbody>${myResults.map(r => `<tr><td>${courses.find(c => c.id === r.courseId)?.code}</td><td>${modules.find(m => m.id === r.moduleId)?.code}</td><td>${r.ca ?? '-'}</td><td>${r.exam ?? '-'}</td><td>${r.total ?? '-'}</td><td><b>${r.grade}</b></td></tr>`).join('')}</tbody></table>
//       <p style="margin-top:40px;color:#666;font-size:12px;">This is an official document generated by EMIS. All approved results are permanently locked.</p>
//       </body></html>`;
//     const blob = new Blob([html], { type: 'text/html' });
//     const url = URL.createObjectURL(blob);
//     const win = window.open(url);
//     if (win) setTimeout(() => win.print(), 500);
//   };

//   const avgTotal = myResults.length ? Math.round(myResults.reduce((s, r) => s + (r.total || 0), 0) / myResults.length) : 0;
//   const passed = myResults.filter(r => r.grade !== 'F' && r.grade !== 'INC').length;

//   if (active === 'dashboard') {
//     return (
//       <div>
//         <PageHeader title={`Welcome, ${currentUser?.name?.split(' ')[0]}`} subtitle="Your academic results portal" />
//         <div className="bg-gradient-to-r from-indigo-700 to-blue-700 rounded-xl p-6 text-white mb-6">
//           <div className="flex items-start justify-between flex-wrap gap-4">
//             <div>
//               <p className="text-blue-200 text-sm">Student Profile</p>
//               <h2 className="text-2xl font-bold mt-1">{currentUser?.name}</h2>
//               <p className="font-mono text-sm mt-1 text-blue-100">{(currentUser as any)?.regNumber}</p>
//               <p className="text-sm mt-1 text-blue-200">{(currentUser as any)?.program} • {(currentUser as any)?.level}</p>
//             </div>
//             <div className="bg-white/10 p-4 rounded-lg"><GraduationCap className="w-12 h-12" /></div>
//           </div>
//         </div>
//         <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
//           <StatCard label="Approved Results" value={myResults.length} icon={FileText} color="bg-emerald-600" />
//           <StatCard label="Modules Passed" value={passed} icon={Award} color="bg-blue-600" />
//           <StatCard label="Average Score" value={avgTotal} icon={Award} color="bg-purple-600" sub="Out of 100" />
//           <StatCard label="Failed/Incomplete" value={myResults.length - passed} icon={History} color="bg-amber-600" />
//         </div>
//         <div className="bg-white border border-slate-200 rounded-xl p-5">
//           <div className="flex items-center justify-between mb-4">
//             <h3 className="font-semibold text-slate-900">Latest Approved Results</h3>
//             <Button onClick={downloadPDF}><Download className="w-4 h-4 inline mr-1" />Download PDF</Button>
//           </div>
//           <Table headers={['Course', 'Module', 'Total', 'Grade']} rowCount={Math.min(myResults.length, 5)}>
//             {myResults.slice(0, 5).map(r => (
//               <tr key={r.id}>
//                 <td className="px-4 py-3 text-xs">{courses.find(c => c.id === r.courseId)?.code} - {courses.find(c => c.id === r.courseId)?.name}</td>
//                 <td className="px-4 py-3 text-xs">{modules.find(m => m.id === r.moduleId)?.code}</td>
//                 <td className="px-4 py-3 text-center font-medium">{r.total ?? '—'}</td>
//                 <td className="px-4 py-3 text-center"><span className={`font-bold ${r.grade === 'F' ? 'text-red-600' : 'text-emerald-600'}`}>{r.grade}</span></td>
//               </tr>
//             ))}
//           </Table>
//           {results.some(r => r.studentId === currentUser?.id && r.status === 'pending') && (
//             <p className="text-xs text-amber-700 bg-amber-50 p-3 rounded mt-3">Note: Some results are still being processed and will appear here once approved.</p>
//           )}
//         </div>
//       </div>
//     );
//   }

//   if (active === 'results') {
//     return (
//       <div>
//         <PageHeader title="My Results" subtitle="Showing only approved (official) results"
//           action={<Button onClick={downloadPDF}><Download className="w-4 h-4 inline mr-1" />Download PDF</Button>} />
//         <div className="bg-white border border-slate-200 rounded-xl p-4 mb-4 grid grid-cols-1 md:grid-cols-3 gap-3">
//           <Select value={filters.courseId} onChange={e => setFilters({ ...filters, courseId: e.target.value })}><option value="">All courses</option>{courses.map(c => <option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</Select>
//           <Select value={filters.moduleId} onChange={e => setFilters({ ...filters, moduleId: e.target.value })}><option value="">All modules</option>{modules.map(m => <option key={m.id} value={m.id}>{m.code}</option>)}</Select>
//           <Select value={filters.sessionId} onChange={e => setFilters({ ...filters, sessionId: e.target.value })}><option value="">All sessions</option>{sessions.map(s => <option key={s.id} value={s.id}>{s.year} {s.semester}</option>)}</Select>
//         </div>
//         <Table headers={['Course', 'Module', 'Session', 'CA', 'Exam', 'Total', 'Grade']} rowCount={filtered.length}>
//           {filtered.map(r => (
//             <tr key={r.id} className="hover:bg-slate-50">
//               <td className="px-4 py-3"><div className="font-medium text-xs">{courses.find(c => c.id === r.courseId)?.code}</div><div className="text-xs text-slate-500">{courses.find(c => c.id === r.courseId)?.name}</div></td>
//               <td className="px-4 py-3 text-xs">{modules.find(m => m.id === r.moduleId)?.name}</td>
//               <td className="px-4 py-3 text-xs">{sessions.find(s => s.id === r.sessionId)?.year}</td>
//               <td className="px-4 py-3 text-center">{r.ca ?? '—'}</td>
//               <td className="px-4 py-3 text-center">{r.exam ?? '—'}</td>
//               <td className="px-4 py-3 text-center font-medium">{r.total ?? '—'}</td>
//               <td className="px-4 py-3 text-center"><span className={`font-bold ${r.grade === 'F' ? 'text-red-600' : 'text-emerald-600'}`}>{r.grade}</span></td>
//             </tr>
//           ))}
//         </Table>
//       </div>
//     );
//   }

//   if (active === 'download') {
//     return (
//       <div>
//         <PageHeader title="Download Results" subtitle="Generate official PDF result slip" />
//         <div className="bg-white border border-slate-200 rounded-xl p-8 text-center max-w-2xl">
//           <div className="bg-blue-50 p-4 rounded-full w-20 h-20 mx-auto mb-4 flex items-center justify-center"><Download className="w-10 h-10 text-blue-700" /></div>
//           <h3 className="text-xl font-bold text-slate-900 mb-2">Official Result Slip</h3>
//           <p className="text-slate-600 mb-6">Generate a printable PDF of all your approved results.</p>
//           <div className="bg-slate-50 p-4 rounded-lg mb-6 text-left">
//             <p className="text-sm"><span className="font-medium">Student:</span> {currentUser?.name}</p>
//             <p className="text-sm"><span className="font-medium">Reg No:</span> {(currentUser as any)?.regNumber}</p>
//             <p className="text-sm"><span className="font-medium">Approved Results:</span> {myResults.length}</p>
//           </div>
//           <Button onClick={downloadPDF}><Download className="w-4 h-4 inline mr-1" />Generate PDF</Button>
//         </div>
//       </div>
//     );
//   }

//   if (active === 'history') {
//     const sorted = [...myResults].sort((a, b) => new Date(b.approvedAt || 0).getTime() - new Date(a.approvedAt || 0).getTime());
//     return (
//       <div>
//         <PageHeader title="Result History" subtitle="Timeline of all approved results" />
//         <div className="bg-white border border-slate-200 rounded-xl p-5">
//           <div className="space-y-4">
//             {sorted.length === 0 && <p className="text-center py-12 text-slate-400">No history yet</p>}
//             {sorted.map(r => {
//               const c = courses.find(x => x.id === r.courseId);
//               const m = modules.find(x => x.id === r.moduleId);
//               return (
//                 <div key={r.id} className="flex items-start gap-4 pb-4 border-b border-slate-100 last:border-0">
//                   <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold text-white ${r.grade === 'F' ? 'bg-red-500' : 'bg-emerald-600'}`}>{r.grade}</div>
//                   <div className="flex-1">
//                     <div className="flex items-center justify-between flex-wrap">
//                       <p className="font-medium text-slate-900">{c?.code} - {c?.name}</p>
//                       <Badge status="approved" />
//                     </div>
//                     <p className="text-sm text-slate-600">{m?.name}</p>
//                     <div className="flex gap-4 text-xs text-slate-500 mt-1">
//                       <span>CA: {r.ca ?? '—'}</span><span>Exam: {r.exam ?? '—'}</span><span>Total: {r.total ?? '—'}</span>
//                       <span>Approved: {r.approvedAt ? new Date(r.approvedAt).toLocaleDateString() : '—'}</span>
//                     </div>
//                   </div>
//                 </div>
//               );
//             })}
//           </div>
//         </div>
//       </div>
//     );
//   }

//   return null;
// };

// export default StudentDash;
